// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFAbE6r3CfUet6iNnOEbmiQGtXxaGlmsE',
    appId: '1:415374477799:web:757c7e8d76e04591509542',
    messagingSenderId: '415374477799',
    projectId: 'flutter-application-1a634',
    authDomain: 'flutter-application-1a634.firebaseapp.com',
    storageBucket: 'flutter-application-1a634.appspot.com',
    measurementId: 'G-ZT1BEPB64H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA18P9By8dgWtY1dEE8hP6VAic1VlvgJWY',
    appId: '1:415374477799:android:59ab1add36214cde509542',
    messagingSenderId: '415374477799',
    projectId: 'flutter-application-1a634',
    storageBucket: 'flutter-application-1a634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3hBvjQTQGYBZqwOKBQPFee5dWgs6YaKU',
    appId: '1:415374477799:ios:8ea54caa095c5ec5509542',
    messagingSenderId: '415374477799',
    projectId: 'flutter-application-1a634',
    storageBucket: 'flutter-application-1a634.appspot.com',
    iosBundleId: 'com.example.flutterApplication17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3hBvjQTQGYBZqwOKBQPFee5dWgs6YaKU',
    appId: '1:415374477799:ios:faf2e61dfa45a88d509542',
    messagingSenderId: '415374477799',
    projectId: 'flutter-application-1a634',
    storageBucket: 'flutter-application-1a634.appspot.com',
    iosBundleId: 'com.example.flutterApplication17.RunnerTests',
  );
}
